apiVersion: apps/v1
kind: Deployment
metadata:
  name: clock-app

spec:
  replicas: 5

  selector:
    matchLabels:
      app: clock-app

  template:
    metadata:
      labels:
        app: clock-app

    spec:
      containers:
      - name: clock-app
        image: oredollar/new-time-app-clock-app:v1

        ports:
        - containerPort: 5000